# Backup of working deployment configuration
# Last updated: March 2024

name: Deploy to Azure

# Triggers: Push to main branch or manual trigger
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: prod  # Important: This environment must exist in GitHub with AZURE_CREDENTIALS secret

    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Set up .NET 9
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Build and publish the app
      - name: Build and Publish
        run: |
          dotnet build BookSearchApp --configuration Release
          dotnet publish BookSearchApp -c Release -o ./publish

      # Login to Azure using service principal
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MonkeysArch'  # Your Azure Web App name
          package: ./publish        # Path to published files 