name: Deploy to Azure

# Only deploy when PRs are merged to main
on:
  pull_request:
    types:
      - closed
    branches: 
      - main

jobs:
  build-and-deploy:
    # Only run if PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build and Publish
        run: |
          dotnet build BookSearchApp --configuration Release
          dotnet publish BookSearchApp -c Release -o ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MonkeysArch'
          package: ./publish 